services:
  frontend:
    build:
      context: .
      target: production
    container_name: chrono_frontend
    network_mode: bridge
    ports:
      - 4100:3000
    env_file:
      - .env
    restart: unless-stopped
