services:
  frontend:
    build:
      context: .
      target: production
    container_name: chrono_frontend
    ports:
      - 4100:3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - chrono

networks:
  chrono:
    external: true